import type { Metadata } from "next";
import React from "react";
import styles from "./Layout.module.scss";
import { Volkhov } from "next/font/google";
import classNames from "classnames";
import { Header } from "@/component/common/Header/Header";
import { Footer } from "@/component/common/Footer/Footer";
import { Providers } from "@/context/Providers";

const volkhov = Volkhov({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const Layout = ({
  children,
}: {
  children: React.ReactNode;
  params: string;
}) => {
  return (
    <html lang="en" className={classNames(styles.root, volkhov.className)}>
      <body className={styles.body}>
        <Header />
        <div className={styles.content}>
          <Providers>{children}</Providers>
        </div>
        <Footer className={styles.footer} />
      </body>
    </html>
  );
};
