import type { Metadata } from "next";
import React from "react";
import styles from "./global.module.scss";
import { Volkhov } from "next/font/google";
import classNames from "classnames";
import { Header } from "@/component/common/Header/Header";

const volkhov = Volkhov({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
  params: string;
}) => {
  return (
    <html lang="en" className={classNames(styles.root, volkhov.className)}>
      <body className={styles.body}>
        <Header />
        <div className={styles.content}>{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
